### ISSUE TITLE
gantt is not defined - webpack 2

### ISSUE THREAD

**Issue by laura-rodriguez** [DHTMLX/react-gantt-demo#2]
Hi,

I am trying to use this in an existent project which uses webpack 2, but I cannot make it works. 
As gantt is defined as global I tried a couple of configurations such as ProvidePlugin or exports-loader without success. 

Any ideas?

Thanks in advance!

**Comment by mperednya** [comment]
Hello.
Have you tried to put "/*global gantt*/" at component top?
Like here https://github.com/DHTMLX/react-gantt-demo/blob/master/src/Gantt.js#L1

**Comment by laura-rodriguez** [comment]
Hi,

Yes I tried that too. The same thing...

**Comment by AlexKlimenkov** [comment]
Hi,
this demo seems working ok with a newer react (react 16.2, react-scripts 1.1 which use webpack 3.8 at the time of writing this), so the error is probably related to integration into your app rather than to compatibility of this code with the latest react/webpack.
I'm closing the issue for now, if it's still actual - please feel free to reopen it and provide a demo/fork repo/etc. where the error could be reproduced
