### ISSUE TITLE
Gantt chart event issue when component updates

### ISSUE THREAD

**Issue by sisardor** [DHTMLX/react-gantt-demo#5]
This seems to be issue is lightbox or eventlisteners, when i go to different page and come back to gantt chart page, and press add task, gantt chart add multiple tasks randomly, if I go to another page and come back again, gantt chart add even more tasks

**Comment by AlexKlimenkov** [comment]
Hi,
it probably has to do with event listeners being attached to gantt instance on each componentDidMount call https://github.com/DHTMLX/react-gantt-demo/blob/8b59f194752ebe41a804877bab220e4cbc7cf36b/src/Gantt.js#L50-L88 - since you have the same gantt instance each time, you'll get duplicated handlers.

Should be fixed here https://github.com/DHTMLX/react-gantt-demo/commit/7e4da1842bcf7d2ce039c3c4751b97c570146d5c
